### ISSUE TITLE
Load roi_id index in order to make classifier work with one trained through the napari-ome-zarr-navigator

### ISSUE THREAD

**Issue by jluethi** [leukemia-kispi/operetta-compose#12]
Hey @fdsteffen,
I'm starting to use some operetta-compose tasks, so I thought I'd open issues when I stumble across something. Here's something I observed, let me know if that works for you.

When training a classifier through the new, full napari-ome-zarr-navigator & napari-feature-classifier workflow with a 0.2.1 version of the classifier, the classifier model is built on a double-indexed df.

The current classifier task just loads the table as-is though, without adding the `roi_id` index column. The values in that index column won't matter, the dataframe just needs to have the same format as the one that it was trained on.

Thus, just using the current version (0.2.2) of the task I get the following error:
```
TASK ERROR: Task name: Label prediction, position in Workflow: 5
TRACEBACK:
Traceback (most recent call last):
  File "/path/to/fractal-server-stable-310/lib/python3.10/site-packages/fractal_server/app/runner/v2/runner_functions_low_level.py", line 111, in run_single_task
    raise e
  File "/path/to/fractal-server-stable-310/lib/python3.10/site-packages/fractal_server/app/runner/v2/runner_functions_low_level.py", line 103, in run_single_task
    _call_command_wrapper(
  File "/path/to/fractal-server-stable-310/lib/python3.10/site-packages/fractal_server/app/runner/v2/runner_functions_low_level.py", line 55, in _call_command_wrapper
    raise TaskExecutionError(err)
fractal_server.app.runner.exceptions.TaskExecutionError: 2024-10-29 14:50:09,148; INFO; START label_prediction task
Traceback (most recent call last):
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/operetta_compose/tasks/label_prediction.py", line 58, in <module>
    run_fractal_task(
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/fractal_tasks_core/tasks/_utils.py", line 79, in run_fractal_task
    metadata_update = task_function(**pars)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pydantic/validate_call_decorator.py", line 60, in wrapper_function
    return validate_call_wrapper(*args, **kwargs)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pydantic/_internal/_validate_call.py", line 96, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/operetta_compose/tasks/label_prediction.py", line 46, in label_prediction
    (ann_tbl.obs[["roi_id", "label"]], features), axis=1
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['roi_id'] not in index"
```

Also, maybe we can consider renaming the task to e.g. "Classify labels"/"Classify objects" or something else where classification is in the name?

**Comment by fdsteffen** [comment]
Thanks @jluethi for reporting this issue. I think we can fix this by dynamically adding a `roi_id` column to the dataframe based the zarr_url and any existing columns identifying the ROI in the anndata `obs` (excluding the `label` and `prediction` columns). This is similar to the logic in the [napari-feature-classifier](https://github.com/fractal-napari-plugins-collection/napari-feature-classifier/blob/0814138307cb70fadad9bb83573d641824a1dd80/src/napari_feature_classifier/classifier.py#L201-L202)

I have tested it with the [napari-ome-zarr-navigator dataset](https://zenodo.org/records/11262587) and it seems functional. Does this work also for you?

Additionally, to clarify the link to the napari-feature-classifier I have renamed the task to `feature_classification` as you suggested.
