### ISSUE TITLE
Document required structure for csv condition table

### ISSUE THREAD

**Issue by jluethi** [leukemia-kispi/operetta-compose#13]
I've wanted to try the condition table task. I'm not sure what the correct layout for such an input table is though.

I tried with the example attached, but then run into the following error. Is the table wrongly formatted? Any idea what could be the issue?

```
TASK ERROR: Task name: Condition registration, position in Workflow: 1
TRACEBACK:
Traceback (most recent call last):
  File "/path/to/server-envs/fractal-server-stable-310/lib/python3.10/site-packages/fractal_server/app/runner/v2/runner_functions_low_level.py", line 111, in run_single_task
    raise e
  File "/path/to/server-envs/fractal-server-stable-310/lib/python3.10/site-packages/fractal_server/app/runner/v2/runner_functions_low_level.py", line 103, in run_single_task
    _call_command_wrapper(
  File "/path/to/server-envs/fractal-server-stable-310/lib/python3.10/site-packages/fractal_server/app/runner/v2/runner_functions_low_level.py", line 55, in _call_command_wrapper
    raise TaskExecutionError(err)
fractal_server.app.runner.exceptions.TaskExecutionError: 2024-10-29 12:52:41,193; INFO; START condition_registration task
Traceback (most recent call last):
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/scope.py", line 231, in resolve
    return self.resolvers[key]
  File "/tungstenfs/landing/fractal/task_python_interpreters/python-310/lib/python3.10/collections/__init__.py", line 986, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/tungstenfs/landing/fractal/task_python_interpreters/python-310/lib/python3.10/collections/__init__.py", line 978, in __missing__
    raise KeyError(key)
KeyError: 'row'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/scope.py", line 242, in resolve
    return self.temps[key]
KeyError: 'row'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/operetta_compose/tasks/condition_registration.py", line 56, in <module>
    run_fractal_task(
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/fractal_tasks_core/tasks/_utils.py", line 79, in run_fractal_task
    metadata_update = task_function(**pars)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pydantic/validate_call_decorator.py", line 60, in wrapper_function
    return validate_call_wrapper(*args, **kwargs)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pydantic/_internal/_validate_call.py", line 96, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/operetta_compose/tasks/condition_registration.py", line 37, in condition_registration
    condition_table = layout.query(
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/frame.py", line 4823, in query
    res = self.eval(expr, **kwargs)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/frame.py", line 4949, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/eval.py", line 336, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 805, in __init__
    self.terms = self.parse()
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 824, in parse
    return self._visitor.visit(self.expr)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 417, in visit_Module
    return self.visit(expr, **kwargs)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 420, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 742, in visit_BoolOp
    return reduce(visitor, operands)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 735, in visitor
    lhs = self._try_visit_binop(x)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 731, in _try_visit_binop
    return self.visit(bop)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 715, in visit_Compare
    return self.visit(binop)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 531, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 451, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 411, in visit
    return visitor(node, **kwargs)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 541, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/ops.py", line 91, in __init__
    self._value = self._resolve_name()
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/ops.py", line 115, in _resolve_name
    res = self.env.resolve(local_name, is_local=is_local)
  File "/path/to/FRACTAL_TASK_DIR/.fractal/operetta-compose0.2.2/venv/lib/python3.10/site-packages/pandas/core/computation/scope.py", line 244, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.errors.UndefinedVariableError: name 'row' is not defined
```

[example_condition_table.csv](https://github.com/user-attachments/files/17559135/example_condition_table.csv)

**Comment by fdsteffen** [comment]
Thank you @jluethi for noticing and reporting this. I could reproduce the error with the example condition table that you provided. The error originates from the `pandas.read_csv()` not parsing the csv that is encoded as `UTF-8 with BOM` correctly. I now adjusted the reader slightly to accomodate for this ():

```python
layout = pd.read_csv(layout_path, sep=None, engine="python", encoding="utf-8-sig", quotechar='"')
layout["col"] = layout["col"].astype(str).str.replace('"', "", regex=False)
```

The new tests are now passed.
